name: CI commit and push
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  commit:
    branches: ["master"]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npm run lint:js
      - run: npm run lint:css
      - run: npm run build